[project]
name = "dns-bench"
version = "1.1.0"
description = "A simple tool to check response times of various DNS servers."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dnspython>=2.7.0", "rich>=14.0.0"]
